@startuml
class resource.TestClient {
+ {static} void main(String[])
}
class resource.Rating {
~ RatingPK key
- double rating
+ RatingPK getKey()
+ void setKey(RatingPK)
+ double getRating()
+ void setRating(double)
+ boolean equals(Object)
+ int hashCode()
}
interface resource.UserRepository {
~ List<User> searchUsers(String)
}
class resource.User {
- String username
- int isContributor
- String fullName
- String password
+ String getFullName()
+ void setFullName(String)
+ String getPassword()
+ void setPassword(String)
+ void setUsername(String)
+ String getUsername()
+ int getIsContributor()
+ void setIsContributor(int)
+ int hashCode()
+ boolean equals(Object)
+ String toString()
}
class resource.RatingController {
- RatingRepository repository
+ List<Rating> getRatings()
+ Rating addRating(Rating)
+ Rating updateRating(Rating,String,String)
+ Rating getRating(String,String)
+ void deleteRating(String,String)
+ List<Rating> getRatingsForExemplar(String)
+ double getAvgRatingForExemplar(String)
}
interface resource.RatingRepository {
~ List<Rating> findRatingsForExemplar(String)
~ double getAvgRatingForExemlar(String)
}
class resource.CommunityController {
- CommunityRepository repository
+ List<Community> getCommunities()
+ Community addCommunity(Community)
+ Community updateCommunity(Community,String)
+ Community getCommunity(String)
+ void deleteCommunity(String)
+ List<Community> getCommunitiesForMember(String)
+ List<Community> searchCommunities(String)
}
class resource.Label {
- String value
+ String getValue()
+ void setValue(String)
+ boolean equals(Object)
+ int hashCode()
}
class resource.UserController {
- {static} UserRepository userRepository
+ {static} UserRepository getUserRepository()
+ {static} void setUserRepository(UserRepository)
+ User addUser(User)
+ User updateUser(User,String)
+ List<User> getUsers()
+ User getUser(String)
+ void deleteUser(String)
+ List<User> searchUsers(String)
}
interface resource.LabelRepository {
}
class resource.ExemplarController {
+ {static} ExemplarRepository repository
+ {static} ExemplarRepository getRepository()
+ void setRepository(ExemplarRepository)
+ List<Exemplar> getExemplars()
+ Exemplar addExemplar(Exemplar)
+ Exemplar updateExemplar(Exemplar,String)
+ Exemplar getExemplar(String)
+ void deleteExemplar(String)
+ List<Exemplar> findExemplarsForCreator(String)
+ List<Exemplar> findExemplarsForContributor(String)
+ List<Exemplar> findExemplarsForUser(String)
+ List<Exemplar> findExemplarsNameLikeXY(String)
+ List<Exemplar> findExemplarsByLabel(String)
}
class com.example.Database.Container.Datenbankverbindung {
+ {static} void main(String[])
}
interface resource.CommunityRepository {
~ List<Community> getCommunitiesForUser(String)
~ List<Community> searchCommunity_NameLikeXY(String)
}
class resource.Exemplar {
- String name
- String problem
- String solution
- User creator
- List<User> contributors
- List<Label> labels
+ List<Label> getLabels()
+ void setLabels(List<Label>)
+ List<User> getContributors()
+ void setContributors(List<User>)
+ String getName()
+ void setName(String)
+ String getProblem()
+ void setProblem(String)
+ String getSolution()
+ void setSolution(String)
+ User getCreator()
+ void setCreator(User)
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}
class resource.LabelController {
- LabelRepository repository
+ List<Label> getLabels()
+ Label addLabel(Label)
+ Label getLabel(String)
+ void deleteLabel(String)
}
class resource.DatabaseContainerApplication {
+ {static} void main(String[])
}
interface resource.ExemplarRepository {
~ List<Exemplar> findExemplarsForCreator(String)
~ List<Exemplar> findExemplarsForContributor(String)
~ List<Exemplar> findExemplarsForUser(String)
~ List<Exemplar> findExemplarsNameLikeXY(String)
~ List<Exemplar> findExemplarsByLabels(String)
}
class resource.Community {
- String name
- List<Exemplar> exemplars
- List<User> members
- User creator
+ String getName()
+ void setName(String)
+ List<Exemplar> getExemplars()
+ void setExemplars(List<Exemplar>)
+ List<User> getMembers()
+ void setUsers(List<User>)
+ User getCreator()
+ void setCreator(User)
+ String toString()
+ boolean equals(Object)
+ int hashCode()
}
class resource.RatingPK {
- User user
- Exemplar exemplar
+ User getUser()
+ void setUser(User)
+ Exemplar getExemplar()
+ void setExemplar(Exemplar)
+ int hashCode()
+ boolean equals(Object)
}


org.springframework.data.jpa.repository.JpaRepository <|-- resource.UserRepository
org.springframework.data.jpa.repository.JpaRepository <|-- resource.RatingRepository
org.springframework.data.jpa.repository.JpaRepository <|-- resource.LabelRepository
org.springframework.data.jpa.repository.JpaRepository <|-- resource.CommunityRepository
org.springframework.data.jpa.repository.JpaRepository <|-- resource.ExemplarRepository
java.io.Serializable <|.. resource.RatingPK
@enduml