@startuml
interface view.listeners.mainframe.exemplarTab.ContributorListener {
~ void frameRequested(ExemplarTab)
}
class view.panels.mainFrame.ContributorLibraryTab {
~ JPanel contributorPanelParent
- List<User> allContributors
- JScrollPane scrollPane
~ Border border
- NewTabListener contributorListener
- Map<String,JCheckBox> selectedContributorMap
~ JPanel buttonPanel
- CloseTabListener closeListener
+ void fetchContributors()
+ void addContributorsToScrollPane()
~ void addComponents()
~ void initializeButtonPanel()
~ void openContributors()
+ void setCloseListener(CloseTabListener)
+ void setContributorListener(NewTabListener)
}
class view.panels.mainFrame.homeTab.MyCommunitiesPanel {
- User user
~ JPanel communityPanelParent
- java.util.List<Community> myCommunities
- List<JPanel> myCommunityPanels
- JScrollPane scrollPane
~ Border border
- NewTabListener newTabListener
~ JPanel buttonPanel
- ActionListener createCommunityListener
~ void fetchCommunites()
~ void addCommunites()
~ void addComponentsCommunity()
~ void initializeButtonPanel()
+ void setNewTabListener(NewTabListener)
+ void setCommuniyListener(NewTabListener)
+ void setCreateExemplarListener(ActionListener)
}
interface view.listeners.mainframe.NewExemplarListener {
~ void NewExemplarRequested(String)
}
class view.frames.mainFrame.MainFrame {
- JTabbedPane tabPanel
~ void addComponents()
+ void addTab(String,Component)
+ void removeTab(Component)
}
interface view.listeners.mainframe.AddContributorListener {
~ void addingRequested(User)
}
interface view.listeners.mainframe.NewRatingListener {
+ void RatingSubmitted(int)
}
class view.panels.mainFrame.exemplarTab.ExemplarTab {
- Exemplar exemplar
- int avgRating
- Label[] labels
- User[] contributors
- ObjectMapper mapper
~ JScrollPane scrollPane
~ JPanel parentPanel
- JPanel metaInfoPanel
- JPanel problemPanel
- JPanel solutionPanel
- JPanel configurationPanel
- JPanel commentPanel
- JPanel labelPanel
- JPanel contributorPanel
~ JTextArea problemTextArea
~ JTextArea solutionTextArea
- JButton closeButton
~ JButton ratingButton
~ JButton commentButton
~ JButton addContributorButton
~ JButton updateButton
~ JButton deleteButton
~ JButton addLabelButton
- CloseTabListener closeListener
- UpdateExemplarListener updateExemplarListener
- DeleteExemplarListener deleteExemplarListener
- AddLabelListener addLabelListener
- RatingListener ratingListener
- ContributorListener contributorListener
- ConfirmExemplarDeletionFrame confirmExemplarDeletionFrame
~ boolean editable
~ void setLayout()
~ Border getBorder(String)
~ void initializeComponents()
- void initializeMetaInfoPanel()
+ void refreshInfoPanel()
- JPanel initializeContributorPanel()
- JPanel initializeLabelPanel()
~ void setEditable()
~ void addComponents()
~ double getAvgRating()
~ void addActionListener()
~ void initializeDeletalFrame()
+ void setCloseListener(CloseTabListener)
+ void setUpdateExemplarListener(UpdateExemplarListener)
+ void setDeleteExemplarListener(DeleteExemplarListener)
+ void setAddLabelListener(AddLabelListener)
+ void setRatingListener(RatingListener)
+ void setContributorListener(ContributorListener)
+ Exemplar getExemplar()
+ JButton getUpdateButton()
+ void setUpdateButton(JButton)
}
interface view.listeners.login.RegisterFormListener {
+ void registrationSubmitted(UserEvent)
}
class view.panels.mainFrame.CommunityTab {
- Community community
- JButton closeButton
- CloseTabListener closeListener
~ void addComponents()
~ void addActionListener()
+ void setCloseListener(CloseTabListener)
}
class view.frames.login.RegisterForm {
~ Container container
~ JLabel title
~ JLabel userNameLabel
~ JLabel fullNameLabel
~ JLabel passwordLabel2
~ JLabel passwordLabel1
~ JLabel contributorLabel
~ JCheckBox contributorCheckBox
~ JTextField userNameText
~ JTextField fullNameText
~ JPasswordField passwordField1
~ JPasswordField passwordField2
~ JButton submitButton
~ JButton resetButton
~ JTextArea welcomeArea
~ Border border
- RegisterFormListener registerFormListener
+ void setLayoutManager()
+ void setLocationAndSize()
+ void styleComponents()
+ void addComponents()
~ void addActionListeners()
+ RegisterFormListener getRegisterFormListener()
+ void setRegisterFormListener(RegisterFormListener)
+ JCheckBox getContributorCheckBox()
+ Container getContainer()
}
class view.frames.mainFrame.NewLabelPopupFrame {
- JPanel infoPanel
- JLabel infoLabel
- JPanel namePanel
- JLabel nameLabel
- JTextField nameField
- JButton button
- ExemplarTab tab
- NewLabelListener listener
+ void setListener(NewLabelListener)
+ ExemplarTab getTab()
+ void setTab(ExemplarTab)
+ void clean()
}
class view.frames.mainFrame.ConfirmExemplarDeletionFrame {
- JPanel parentPanel
- JLabel label
- JTextField textField
- JButton button
- ActionListener confirmListener
- String exemplarName
+ ActionListener getConfirmListener()
+ void setConfirmListener(ActionListener)
}
interface view.listeners.mainframe.exemplarTab.AddLabelListener {
+ void buttonClicked(ExemplarTab)
}
interface view.listeners.mainframe.NewCommunityListener {
~ void NewCommunityRequested(String)
}
class view.frames.mainFrame.NewExemplarPopupFrame {
- JPanel infoPanel
- JLabel infoLabel
- JPanel namePanel
- JLabel nameLabel
- JTextField nameField
- JButton button
- NewExemplarListener listener
+ void setListener(NewExemplarListener)
+ void clean()
}
class view.panels.mainFrame.homeTab.HomeTab {
~ User user
~ JPanel communitiesAndProfile
~ ProfilePanel profilePanel
~ MyExemplarsPanel myExemplarsPanel
~ MyCommunitiesPanel myCommunitiesPanel
~ Border border
~ void initializePanels()
~ Border createBorder(String)
+ void refresh()
+ void setUpdateUserListener(ProfilePanelListener)
+ void setDeleteUserListener(ProfilePanelListener)
+ void setOpenExemplarListener(NewTabListener)
+ void setOpenCommunityListener(NewTabListener)
+ void setCreateExemplarListener(ActionListener)
+ void setUser(User)
+ ProfilePanel getProfilePanel()
+ void setCreateExemplarLibraryListener(ActionListener)
+ void setCreateContributorLibraryListener(ActionListener)
}
class view.frames.mainFrame.NewCommunityPopupFrame {
- JPanel infoPanel
- JLabel infoLabel
- JPanel namePanel
- JLabel nameLabel
- JTextField nameField
- JButton button
- NewCommunityListener listener
+ void setListener(NewCommunityListener)
+ void clean()
}
interface view.listeners.mainframe.exemplarTab.DeleteExemplarListener {
~ void deleteRequested(String,ExemplarTab)
}
interface view.listeners.mainframe.NewLabelListener {
~ void labelRequested(String)
}
interface view.listeners.mainframe.CloseTabListener {
~ void shutdownRequested(Component)
}
class view.events.UserEvent {
- String username
- String fullname
- String password
- int isContributor
+ String getUsername()
+ void setUsername(String)
+ String getFullname()
+ void setFullname(String)
+ String getPassword()
+ void setPassword(String)
+ int getIsContributor()
+ void setIsContributor(int)
}
interface view.listeners.mainframe.homeTab.ProfilePanelListener {
+ void updateRequested(User)
}
class view.frames.login.LoginFrame {
~ Container container
~ JLabel userLabel
~ JLabel passwordLabel
~ JTextField userTextField
~ JPasswordField passwordField
~ JButton loginButton
~ JButton resetButton
~ JButton guestButton
~ JButton registerButton
~ JCheckBox showPassword
~ LoginListener loginListener
~ RegisterButtonListener registerListener
~ JLabel title
+ void setLayoutManager()
+ void setLocationAndSize()
+ void addComponentsToContainer()
+ void addListenersToComponents()
+ LoginListener getLoginListener()
+ void setLoginListener(LoginListener)
+ void actionPerformed(ActionEvent)
+ void setRegisterListener(RegisterButtonListener)
+ JButton getLoginButton()
+ Container getContainer()
+ JCheckBox getShowPassword()
}
class view.panels.mainFrame.homeTab.ProfilePanel {
~ JLabel userNameLabel
~ JLabel fullNameLabel
~ JLabel oldPasswordLabel
~ JLabel passwordLabel2
~ JLabel passwordLabel1
~ JTextField userNameText
~ JTextField fullNameText
~ JPasswordField oldPasswordField
~ JPasswordField passwordField1
~ JPasswordField passwordField2
~ JLabel contributorLabel
~ JCheckBox contributorCheckBox
~ JButton updateButton
~ JButton deleteUserButton
~ User user
~ ProfilePanelListener updateListener
~ ProfilePanelListener deleteListener
- ConfirmDeletalFrame confirmFrame
~ void addComponents()
~ void setData()
~ void addActionListener()
~ void initializeConfirmFrame()
+ void setUser(User)
+ void setUpdateUserListener(ProfilePanelListener)
+ void setDeleteListener(ProfilePanelListener)
}
class view.panels.mainFrame.homeTab.ProfilePanel.ConfirmDeletalFrame {
~ ActionListener confirmedListener
~ ActionListener cancelledListener
- JButton confirmButton
- JButton cancelButton
- JPanel buttonPanel
- JPanel panel
- JLabel label
~ void addListeners()
+ void setConfirmedListener(ActionListener)
+ void setCancelledListener(ActionListener)
}
class view.panels.mainFrame.AllExemplarsPanel {
- JScrollPane scrollPane
- JList exemplarList
~ DefaultListModel<String> listModel
- List<Exemplar> exemplars
- JButton showExemplarButton
- ExemplarClient exemplarClient
- JButton closeButton
}
class view.frames.mainFrame.AddUserrFrame {
- ExemplarTab tab
- JPanel parentPanel
- JTextField searchField
- JButton searchButton
- JPanel searchPanel
- JList<User> searchList
- List<User> foundUsers
- JButton addButton
- JScrollPane listScroller
- UserClient client
- AddContributorListener listener
~ void initializeComponents()
~ void addComponents()
~ User[] fetchUsers(String)
~ void addActionListeners()
+ ExemplarTab getTab()
+ void setTab(ExemplarTab)
+ void setListener(AddContributorListener)
}
class view.frames.mainFrame.NewRatingPopupFrame {
- Exemplar exemplar
- ExemplarTab tab
- JLabel label
- JPanel parentPanel
- int RATING_MIN
- int RATING_MAX
- int RATING_INI
- JSlider slider
- JButton button
- NewRatingListener listener
+ Exemplar getExemplar()
+ void setExemplar(Exemplar)
+ void setListener(NewRatingListener)
+ ExemplarTab getTab()
+ void setTab(ExemplarTab)
}
interface view.listeners.mainframe.homeTab.NewTabListener {
+ void tabRequested(List<String>)
}
interface view.listeners.mainframe.exemplarTab.UpdateExemplarListener {
~ void updateRequested(Exemplar)
}
class view.panels.mainFrame.contributorTab.ContributorTab {
- User contributor
- double avgRating
- List<Label> labels
- List<Exemplar> exemplars
- ObjectMapper mapper
~ JScrollPane scrollPane
~ JPanel parentPanel
- JPanel metaInfoPanel
- JPanel configurationPanel
- JPanel labelPanel
- JPanel contributorPanel
- JButton closeButton
- CloseTabListener closeListener
- ContributorListener contributorListener
- ConfirmExemplarDeletionFrame confirmExemplarDeletionFrame
~ void setLayout()
~ Border getBorder(String)
~ void initializeComponents()
- void initializeMetaInfoPanel()
+ void refreshInfoPanel()
- JPanel initializeLabelPanel()
~ void addComponents()
~ double getAvgRating()
~ List<Label> getLabels()
~ void addActionListener()
+ void setCloseListener(CloseTabListener)
+ User getContributor()
}
interface view.listeners.mainframe.exemplarTab.RatingListener {
+ void ratingRequested(ExemplarTab)
}
class view.panels.mainFrame.homeTab.MyExemplarsPanel {
- User user
~ JPanel exemplarPanelParent
- List<Exemplar> myExemplars
- JScrollPane scrollPane
~ Border border
- NewTabListener exemplarListener
- Map<String,JCheckBox> selectedExemplarMap
~ JPanel buttonPanel
~ ActionListener exemplarLibraryListener
~ ActionListener contributorLibraryListener
- ActionListener createExemplarListener
+ void fetchExemplars()
+ void addExemplarsToScrollPane()
~ void initializeButtonPanel()
~ void addComponents()
~ void openExemplars()
+ void setExemplarListener(NewTabListener)
+ void setCreateExemplarListener(ActionListener)
+ void setCreateExemplarLibraryListener(ActionListener)
+ void setCreateContributorLibraryListener(ActionListener)
}
interface view.listeners.login.LoginListener {
+ void loginRequested(String,String)
}
interface view.listeners.login.RegisterButtonListener {
~ void registerFormRequested()
}
class view.panels.mainFrame.ExemplarLibraryTab {
~ JPanel exemplarPanelParent
- List<Exemplar> allExemplars
- JScrollPane scrollPane
~ Border border
- NewTabListener exemplarListener
- Map<String,JCheckBox> selectedExemplarMap
~ JPanel buttonPanel
- CloseTabListener closeListener
+ void fetchExemplars()
+ void addExemplarsToScrollPane()
~ void addComponents()
~ void initializeButtonPanel()
~ void openExemplars()
+ void setCloseListener(CloseTabListener)
+ void setExemplarListener(NewTabListener)
+ void updateTab()
}


view.panels.mainFrame.JPanel <|-- view.panels.mainFrame.ContributorLibraryTab
view.panels.mainFrame.homeTab.JPanel <|-- view.panels.mainFrame.homeTab.MyCommunitiesPanel
view.frames.mainFrame.JFrame <|-- view.frames.mainFrame.MainFrame
view.panels.mainFrame.exemplarTab.JPanel <|-- view.panels.mainFrame.exemplarTab.ExemplarTab
view.panels.mainFrame.JPanel <|-- view.panels.mainFrame.CommunityTab
view.frames.login.JFrame <|-- view.frames.login.RegisterForm
view.frames.mainFrame.JFrame <|-- view.frames.mainFrame.NewLabelPopupFrame
view.frames.mainFrame.JFrame <|-- view.frames.mainFrame.ConfirmExemplarDeletionFrame
view.frames.mainFrame.JFrame <|-- view.frames.mainFrame.NewExemplarPopupFrame
view.panels.mainFrame.homeTab.JPanel <|-- view.panels.mainFrame.homeTab.HomeTab
view.frames.mainFrame.JFrame <|-- view.frames.mainFrame.NewCommunityPopupFrame
java.awt.event.ActionListener <|.. view.frames.login.LoginFrame
view.frames.login.JFrame <|-- view.frames.login.LoginFrame
view.panels.mainFrame.homeTab.JPanel <|-- view.panels.mainFrame.homeTab.ProfilePanel
view.panels.mainFrame.homeTab.ProfilePanel +.. view.panels.mainFrame.homeTab.ProfilePanel.ConfirmDeletalFrame
view.panels.mainFrame.homeTab.JFrame <|-- view.panels.mainFrame.homeTab.ProfilePanel.ConfirmDeletalFrame
view.panels.mainFrame.JPanel <|-- view.panels.mainFrame.AllExemplarsPanel
view.frames.mainFrame.JFrame <|-- view.frames.mainFrame.AddUserrFrame
view.frames.mainFrame.JFrame <|-- view.frames.mainFrame.NewRatingPopupFrame
view.panels.mainFrame.contributorTab.JPanel <|-- view.panels.mainFrame.contributorTab.ContributorTab
view.panels.mainFrame.homeTab.JPanel <|-- view.panels.mainFrame.homeTab.MyExemplarsPanel
view.panels.mainFrame.JPanel <|-- view.panels.mainFrame.ExemplarLibraryTab
@enduml