@startuml
skinparam classAttributeIconSize 0
package controller{
class FrameController{
#currentUser : Users
#currentExemplar : Exemplar
--
Frames
--
#mainFrame : MainFrame
#userFrame : UserFrame
#communityFrame : CommunityFrame
}
}

package view{
class MainFrame extends JFrame{
#exemplarPanel : ExemplarPanel
#allExemplarsPanel : AllExemplarsPanel
#menuBar : MenuBar
}
class MenuBar extends JMenuBar{

}
class UserFrame extends JFrame{
#user : Users
}

class CommunityFrame extends JFrame{
#community : Community
}
class ExemplarPanel extends JPanel{
#exemplar : Exemplar
}
class AllExemplarsPanel extends JPanel{
exemplars : List<Exemplar>
}
}

package model{
package entities{

class Exemplar{
#owner : Contributor
#problem : String
#solution : String
}

class Users{
#username : String
#password : String
}

class Contributor{

}
Contributor --|> Users


class Label{
 #value : String
}


class Community{
#name : String
#creator : Users
}

class Rating{
#exemplar : Exemplar
#rater : Users
#rating : int
}
}
package httpClients{
abstract class Client<T>{
#client : HttpClient
#request : HttpRequest
#response : HttpResponse
#mapper : ObjectMapper
#url : String
void add(T value)
T get(String id)
T[] getAll()
void delete (String id)
}

class UserClient<Users> extends Client{
}
class ExemplarClient<Exemplar> extends Client{
void addLabelToExemplar(Exemplar e, Label l)
void addContributorToExemplar(Exemplar e, Contributor c)
void addRatingToExemplar(Rating r)

List<Contributor> getContributors(Exemplar e)
List<Rating> getRatings(Exemplar e)
List<Label> getLabels(Exemplar e)
}
class CommunityClient<Community> extends Client{
void addAdministratorToCommunity(Community c, Users u)
void addMemberToCommunity(Community c, Users u)
void addExemplarToCommunity(Community c, Users u)

List<Users> getAdministratorsOfComm(Community c)
List<Users> getMembersOfCOmm((Community c)
List<Exemplar> getExemplarsOfComm(Community c)

void rmvAdminOfCommunity(Community c, Users u)
void rmvMemberOfCommunity(Community c, Users u)
void rmvExemplarOfCommunity(Community c, Exemplar e)
}

class LabelClient<Label> extends Client{
void addLabelToExemplar(Label l, Exemplar e)
List<Label> getLabelsForExemplar(Exemplar e)
void rmvLabelFromExemplar(Exemplar e, Label l)
}

class RatingClient<Rating> extends Client{
void addRatingToExemplar(Exemplar e, Rating r)
void removeRatingFromExemplar(Exemplar e, Rating r)
List<Rating> getRatingsForExemplar(Exemplar e)
}
}
}
@enduml
